### ISSUE TITLE
AttributeError: partially initialized module 'latextools' has no attribute 'render_snippet' 

### ISSUE THREAD

**Issue by eidoom** [cduck/latextools#2]
OS: Fedora 35
Python: 3.10

Attempting to run [the first example](https://github.com/cduck/latextools#easily-render-a-bit-of-latex-code) yields
```shell
Traceback (most recent call last):
  File "/home/USER/scratch/latex2svg/latextools.py", line 1, in <module>
    import latextools
  File "/home/USER/scratch/latex2svg/latextools.py", line 4, in <module>
    latex_eq = latextools.render_snippet(
AttributeError: partially initialized module 'latextools' has no attribute 'render_snippet' (most likely due to a circular import)
```

**Comment by cduck** [comment]
Thanks for the bug report.

The issue here is a name conflict between your script `latextools.py` and the module `latextools`, not an issue with the package.  When you write `import latextools` Python checks your current directory for `.py` files before checking for installed packages.  This causes a circular import where your script imports itself, similar to [this one](https://bugs.python.org/issue21924).

Fix: rename your script to something other than `latextools.py`.

**Comment by eidoom** [comment]
Thank you for the very clear explanation!
